### Probe Module to use
probe-module udp

### Destination port to scan
target-port 20000
rate 7000

### DNP3 UDP payload (Link Layer request frame)
probe-args hex:0564050c8001000000000000

### Output
output-module json
output-filter "success=1 && repeat=0"
output-fields "saddr,sport,daddr,dport,timestamp_str"

