### Probe Module to use
probe-module tcp_synscan

### Destination port to scan
target-port 102,502,2404,10001,20000
rate 7000


### Output
output-module json
output-filter "success=1 && repeat=0"
output-fields "saddr,sport,ttl,window,tcpopt_wscale,tcpopt_mss,timestamp_str"
